version: '3'

services:
  minecraft:
    build: ./Dockerfile
    expose:
      - "25566"
      - "25562"
      - "8123"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./worlds/world:/world/
      - ./worlds/world_nether:/world_nether/
      - ./worlds/world_the_end:/world_the_end/

  dockercraft:
    build: ./dockercraft
    expose:
      - "25565"
    container_name: Dockercraft
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    tty: true

  haproxy:
    build: ./haproxy
    container_name: ggHaproxy
    env_file:
      - .env
    links:
      - minecraft
      - rcon
    ports:
      - "36543:36543"
      - "8080:8080"
      - "8123:8123"
    network_mode: "bridge"
    tty: true 
    stdin_open: true
    depends_on:
      - minecraft
    restart: unless-stopped

  rcon:
    build: ./rcon
    container_name: ggRcon
    env_file:
      - .env
    links:
      - minecraft
    expose:
      - "80"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    depends_on:
      - minecraft
    restart: always
