version: '3'

services:
  minecraft:
    build: ./Dockerfile
    container_name: ggMinecraft
    environment:
      server.public.port: 25566
      server.hostname: ${SERVER_HOSTNAME}
    ports:
      - "25566:25566"
      - "25562:25562"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./world:/world/

  haproxy:
    build: ./haproxy
    container_name: ggHaproxy
    links:
      - minecraft
    ports:
      - "36543:36543"
    network_mode: "bridge"
    tty: true 
    stdin_open: true
    depends_on:
      - minecraft
    restart: unless-stopped
  rcon:
    build: ./rcon
    container_name: ggrcon
    links:
      - minecraft
    ports:
      - "8080:80"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    depends_on:
      - minecraft
    restart: always
