version: '3'

services:
  minecraft:
    build: ./Dockerfile
    expose:
      - "25566"
      - "25562" 
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./world:/world/

  haproxy:
    build: ./haproxy
    container_name: ggHaproxy
    env_file:
      - .env
    links:
      - minecraft
      - rcon
    ports:
      - "36543:36543"
      - "8080:8080"
    network_mode: "bridge"
    tty: true 
    stdin_open: true
    depends_on:
      - minecraft
    restart: unless-stopped

  rcon:
    build: ./rcon
    container_name: ggRcon
    env_file:
      - .env
    links:
      - minecraft
    expose:
      - "80"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    depends_on:
      - minecraft
    restart: always
