version: '3'

services:
  minecraft:
    build: ./Dockerfile
    environment:
        server.hostname: ${SERVER_HOSTNAME}
    expose:
      - "25566"
      - "25562" 
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./world:/world/

  haproxy:
    build: ./haproxy
    container_name: ggHaproxy
    environment:
      - DIR=docker-tihi
    links:
      - minecraft
    ports:
      - "36543:36543"
    network_mode: "bridge"
    tty: true 
    stdin_open: true
    depends_on:
      - minecraft
    restart: unless-stopped

  rcon:
    build: ./rcon
    container_name: ggRcon
    links:
      - minecraft
    ports:
      - "8080:80"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    depends_on:
      - minecraft
    restart: always
