version: '3'

services:
  minecraft:
    build: ./Dockerfile
    expose:
      - "25566"
      - "25562"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
    volumes:
      - ./world:/world/
      - ./world_nether:/world_nether/
      - ./world_the_end:/world_the_end/
    ports:
     - "8123:8123"
  minecraftback:
    build: ./back
    expose:
      - "25566"
      - "25562"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always

  dockercraft:
    build: ./dockercraft
    container_name: Dockercraft
    volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
     - "25565:25565"
    tty: true

  haproxy:
    build: ./haproxy
    container_name: ggHaproxy
    env_file:
      - .env
    links:
      - minecraft
      - minecraftback
      - rcon
    ports:
      - "36543:36543"
      - "8080:8080"
    network_mode: "bridge"
    tty: true 
    stdin_open: true
    depends_on:
      - minecraft
      - minecraftback
    restart: unless-stopped

  rcon:
    build: ./rcon
    container_name: ggRcon
    env_file:
      - .env
    links:
      - minecraft
      - minecraftback
    expose:
      - "80"
    network_mode: "bridge"
    tty: true
    stdin_open: true
    depends_on:
      - minecraft
      - minecraftback
    restart: always
